# This file is a template, and might need editing before it works on your project.
# Official docker image.
#image: docker:latest

#services:
#  - docker:dind

#before_script:
#  - docker login -u "mosti94" -p "Nettavisen123+" docker.io

#build-master:
#  stage: build
#  script:
#    - docker build -f "HvZ/Dockerfile" -t "$CI_REGISTRY_IMAGE" .
#    - docker push "$CI_REGISTRY_IMAGE:latest"
#  only:
#    - main
#  when: manual

name: CI/CD Pipeline

# Definerer at pipeline skal kjøre når det skjer en endring på hovedgrenen (main)
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Definerer jobben "Build"
# Dette er en jobb som bygger et Docker-bilde av applikasjonen vår
# og pusher den til et Docker-bilde-register (f.eks. Docker Hub)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: username/repo-name:latest
